force-app/main/default/objects/ALK_Invoice__c/ALK_Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>No de la Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_Case__c.field-meta.xml
<CustomField>
    <fullName>ALK_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_EAN__c.field-meta.xml
<CustomField>
    <fullName>ALK_EAN__c</fullName>
    <label>EAN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Delivery_Email__c.field-meta.xml
<CustomField>
    <fullName>ALK_Delivery_Email__c</fullName>
    <label>Correo del Entregador</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ALK_ODS.recordType-meta.xml
<RecordType>
    <fullName>ALK_ODS</fullName>
    <active>true</active>
    <businessProcess>ODS</businessProcess>
    <label>ODS</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Persona Natural</label>
</RecordType>

force-app/main/default/classes/ALK_SendODSReportEmailTest.cls
@isTest 
public class ALK_SendODSReportEmailTest {

    @isTest public static void test() {
        Account a = new Account(FirstName = 'testAccountSA', 
                                LastName = 'Last', 
                                PersonEmail='test@test.com',
                                Phone='573005716885',
                                ALK_WHATSAPP__c = false,
                                ALK_SMS__c = false,
                                ALK_EMAIL__c = true,
                                RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId());
        insert a;        
        
        Case ods = new Case(AccountId = a.Id, 
                              Origin = 'ODS Demanda', 
                              Priority = 'Media', 
                              Subject = 'ODS', 
                              Status = 'Nuevo',
                              ALK_Delivery_Email__c = 'test@test.com',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_ODS').getRecordTypeId());        

        insert ods;
        
        ALK_Invoice__c iods = new alk_Invoice__c();
        iods.ALK_Case__c = ods.Id;
        iods.ALK_EAN__c = '12345';
        iods.Name = '12345';        
        
        insert iods;
        
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        insert contentVersion;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = ods.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;  
        
        Test.startTest();
        List<String> result = ALK_SendODSReportEmail.sendODSReport(new List<String>{ods.Id});
        
        System.assertEquals('SUCCESS', result.get(0));
        Test.stopTest();
    }
}