force-app/main/default/objects/ALK_Invoice__c/ALK_Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>No de la Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_Case__c.field-meta.xml
<CustomField>
    <fullName>ALK_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_EAN__c.field-meta.xml
<CustomField>
    <fullName>ALK_EAN__c</fullName>
    <label>EAN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Approval_Number__c.field-meta.xml
<CustomField>
    <fullName>ALK_Approval_Number__c</fullName>
    <externalId>true</externalId>
    <label>Número de Aprobación</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Motivo_de_Cierre__c.field-meta.xml
<CustomField>
    <fullName>ALK_Motivo_de_Cierre__c</fullName>
    <description>El usuario selecciona el motivo por el cual desea cerrar el caso</description>
    <inlineHelpText>Por favor, seleccione el motivo por el cual desea cerrar el caso</inlineHelpText>
    <label>Motivo de Cierre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A FAVOR DE CLIENTE ASUME ALKOSTO</fullName>
            </value>
            <value>
                <fullName>A FAVOR DE CLIENTE ASUME MARCA</fullName>
            </value>
            <value>
                <fullName>CLIENTE DESISTE DE RECLAMACIÓN</fullName>
            </value>
            <value>
                <fullName>NEGATIVA SOLICITUD DE CLIENTE</fullName>
            </value>
            <value>
                <fullName>PRODUCTO FUNCIONAL</fullName>
            </value>
            <value>
                <fullName>SIN CONTACTO CON CLIENTE</fullName>
            </value>
            <value>
                <fullName>SOLUCION CLIENTE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Pak_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>ALK_Pak_Batch_Status__c</fullName>
    <label>Estado proceso batch Pak</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procesado</fullName>
                <default>true</default>
                <label>No procesado</label>
            </value>
            <value>
                <fullName>ODS/PQR relacionados</fullName>
            </value>
            <value>
                <fullName>ODS/PQR Cerrados</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Estado__c.field-meta.xml
<CustomField>
    <fullName>Sub_Estado__c</fullName>
    <label>Sub-Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Almacenado en tienda</fullName>
            </value>
            <value>
                <fullName>Carta enviada</fullName>
            </value>
            <value>
                <fullName>Carta no entregada</fullName>
            </value>
            <value>
                <fullName>Cliente no contactado</fullName>
            </value>
            <value>
                <fullName>Cliente no recibe</fullName>
            </value>
            <value>
                <fullName>Cliente no recoge</fullName>
            </value>
            <value>
                <fullName>Cte Contactado Pte Recogida</fullName>
            </value>
            <value>
                <fullName>Destrucción</fullName>
            </value>
            <value>
                <fullName>Entregado Cliente</fullName>
            </value>
            <value>
                <fullName>Enviado a CENTR</fullName>
            </value>
            <value>
                <fullName>Enviado a Cliente</fullName>
            </value>
            <value>
                <fullName>Recibido en CENTR</fullName>
            </value>
            <value>
                <fullName>Retornado a Tienda</fullName>
            </value>
            <value>
                <fullName>Pendiente envío a CENTR</fullName>
            </value>
            <value>
                <fullName>Caso SIC</fullName>
            </value>
            <value>
                <fullName>En espera de Respuesta</fullName>
            </value>
            <value>
                <fullName>Cliente Informado</fullName>
            </value>
            <value>
                <fullName>Alkosto</fullName>
            </value>
            <value>
                <fullName>Marca</fullName>
            </value>
            <value>
                <fullName>Producto Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado Bono Cambio</fullName>
            </value>
            <value>
                <fullName>Entregado a Centro Servicio en Tienda</fullName>
            </value>
            <value>
                <fullName>Entregado a Centro Servicio en CENTR</fullName>
            </value>
            <value>
                <fullName>Recibo/Entrega - Falla</fullName>
            </value>
            <value>
                <fullName>Recibo/Entrega - Deteriorado/cosmetico</fullName>
            </value>
            <value>
                <fullName>Recibo/Entrega - Incompleto</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Enviado a Tienda</fullName>
            </value>
            <value>
                <fullName>En CENTR de tienda</fullName>
            </value>
            <value>
                <fullName>En muelle CAS pte validacion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ALK_ODS.recordType-meta.xml
<RecordType>
    <fullName>ALK_ODS</fullName>
    <active>true</active>
    <businessProcess>ODS</businessProcess>
    <label>ODS</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_PAK.recordType-meta.xml
<RecordType>
    <fullName>ALK_PAK</fullName>
    <active>true</active>
    <businessProcess>PAK</businessProcess>
    <label>PAK</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_QUEJA.recordType-meta.xml
<RecordType>
    <fullName>ALK_QUEJA</fullName>
    <active>true</active>
    <businessProcess>Quejas</businessProcess>
    <label>QUEJA</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_SOLICITUD.recordType-meta.xml
<RecordType>
    <fullName>ALK_SOLICITUD</fullName>
    <active>true</active>
    <businessProcess>SOLICITUDES</businessProcess>
    <label>SOLICITUD</label>
</RecordType>

force-app/main/default/classes/ALK_CloseRelatedCasesClosedPaksBatch.cls
public without sharing class ALK_CloseRelatedCasesClosedPaksBatch Extends ALK_StandardBatch {
    public List<ALK_Invoice__c> start(Database.BatchableContext BC){
        List<ALK_Invoice__c> scope = [SELECT Id,
                NAME,
                ALK_EAN__c,
                ALK_Case__c,
                ALK_Case__r.CaseNumber,
                ALK_Case__r.ALK_Approval_Number__c
                From ALK_Invoice__c 
                Where ALK_Case__r.ALK_Pak_Batch_Status__c = 'ODS/PQR relacionados' AND
                ALK_Case__r.RecordTypeId = :Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_PAK').getRecordTypeId() AND
                (ALK_Case__r.Status = 'Solicitud Finalizada con devolución' OR ALK_Case__r.Status = 'No hay solicitudes pendientes')];
        
        System.debug('scope -> ' + scope);
        
        return scope;
    }

    public void execute(Database.BatchableContext BC, List<ALK_Invoice__c> scope){
        List<String> invoiceNuList = new List<String>();
        List<String> eanNuList = new List<String>();
        List<String> caseRTIdList = new List<String>{
            Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_ODS').getRecordTypeId(),
            Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_QUEJA').getRecordTypeId(),
            Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_SOLICITUD').getRecordTypeId()};
        List<String> statusListQueja = new List<String>{'New', 'En Progreso', 'En espera del cliente', 'En espera del Proveedor'};
        List<String> statusListODS = new List<String>{'Cambio Evitado Gestión Técnico','Anulación de ODS','Abandono Cliente;','Solución al cliente'};            
        List<Case> casesToBeUpdated = new List<Case>();
        Map<String,String> caseNumberMap = new Map<String,String>();
        Map<String,String> caseApprovalNumberMap = new Map<String,String>(); 
        List<String> pakCaseIdList = new List<String>();         
        List<FeedItem> posts = new List<FeedItem>();
        Map<String,String> relatedCaseIdClosedReasonMap = new Map<String,String>();                      
        Map<String,String> relatedCaseIdClosedStateMap = new Map<String,String>();                      
        
        if (scope.size() > 0) {
            
            for(ALK_Invoice__c i : scope) {
                invoiceNuList.add(i.Name);
                eanNuList.add(i.ALK_EAN__c);
                caseNumberMap.put(i.Name+i.ALK_EAN__c,i.ALK_Case__r.CaseNumber);
                caseApprovalNumberMap.put(i.Name+i.ALK_EAN__c,i.ALK_Case__r.ALK_Approval_Number__c);
                pakCaseIdList.add(i.ALK_Case__c);
            }

            List<ALK_Invoice__c> relatedInvoiceList = this.getRelatedInvoices(caseRTIdList, invoiceNuList, eanNuList, statusListQueja, statusListODS);
            
            for(ALK_Invoice__c i : relatedInvoiceList) {
                posts.add(new FeedItem(ParentId = i.ALK_Case__c, Body=String.format(System.Label.ALK_Related_Pak_Closed_Reason, new string[]{caseNumberMap.get(i.Name+i.ALK_EAN__c)})));
                relatedCaseIdClosedReasonMap.put(i.ALK_Case__c,
                                                caseApprovalNumberMap.get(i.Name+i.ALK_EAN__c).startsWithIgnoreCase('AP') 
                                                ? 'A FAVOR DE CLIENTE ASUME ALKOSTO'
                                                : 'A FAVOR DE CLIENTE ASUME MARCA');
                relatedCaseIdClosedStateMap.put(i.ALK_Case__c,
                                                i.ALK_Case__r.RecordType.DeveloperName == 'ALK_ODS' 
                                                ? 'Solución al Cliente;Entregado Bono Cambio'
                                                : 'Cerrado');
            }
            
            for(Case c : [Select Id, Status, Sub_Estado__c , RecordType.DeveloperName, ALK_Motivo_de_Cierre__c From Case Where Id = :relatedCaseIdClosedReasonMap.keySet()]) {
            	String[] status = relatedCaseIdClosedStateMap.get(c.Id).split(';');
                System.debug('status=>'+status);
                System.debug('RecordType.DeveloperName=>'+c.RecordType.DeveloperName);
                
                c.Status = status[0];
                if(c.RecordType.DeveloperName == 'ALK_ODS') {
                    c.Sub_Estado__c = status[1];	                    
                }
                c.ALK_Motivo_de_Cierre__c = relatedCaseIdClosedReasonMap.get(c.Id);
                
                casesToBeUpdated.add(c);
            } 
            
            for(Case c : [Select Id, ALK_Pak_Batch_Status__c From Case Where Id = :pakCaseIdList]) {
                c.ALK_Pak_Batch_Status__c = 'ODS/PQR Cerrados';
                
                casesToBeUpdated.add(c);                
            }
            
            if (casesToBeUpdated.size() > 0) {
	            update casesToBeUpdated;              
            } 

            if (posts.size() > 0) {
                insert posts;             
            }                         
        }
    }
   
    private List<ALK_Invoice__c> getRelatedInvoices(List<String> caseRTIdList, List<String> invoiceNuList, List<String> eanNuList, List<String> statusListQueja, List<String> statusListODS) {
        List<ALK_Invoice__c> result = new List<ALK_Invoice__c>();
        
        for(ALK_Invoice__c i : [SELECT Name, ALK_Case__c, ALK_EAN__c, ALK_Case__r.ALK_Approval_Number__c,ALK_Case__r.Status, ALK_Case__r.RecordType.DeveloperName
                From ALK_Invoice__c                                 
                Where ALK_Case__r.RecordTypeId = :caseRTIdList AND                                
                Name = :invoiceNuList AND                                
                                ALK_EAN__c = :eanNuList]) {
                                    if ((i.ALK_Case__r.RecordType.DeveloperName == 'ALK_ODS') && (!statusListODS.contains(i.ALK_Case__r.Status))) {
                                    	result.add(i);    
                                    } else if((i.ALK_Case__r.RecordType.DeveloperName != 'ALK_ODS') && (statusListQueja.contains(i.ALK_Case__r.Status))) {
                                    	result.add(i);                                            
                                    }
                                }
        return result;
    }
    
    protected override String getBatchName() {
        return 'Close related Pak\'s ODS and PQR';
    }         
}