force-app/main/default/objects/ALK_Invoice__c/ALK_Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>No de la Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_Case__c.field-meta.xml
<CustomField>
    <fullName>ALK_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_EAN__c.field-meta.xml
<CustomField>
    <fullName>ALK_EAN__c</fullName>
    <label>EAN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Pak_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>ALK_Pak_Batch_Status__c</fullName>
    <label>Estado proceso batch Pak</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procesado</fullName>
                <default>true</default>
                <label>No procesado</label>
            </value>
            <value>
                <fullName>ODS/PQR relacionados</fullName>
            </value>
            <value>
                <fullName>ODS/PQR Cerrados</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Related_ODS__c.field-meta.xml
<CustomField>
    <fullName>ALK_Related_ODS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso ODS Relacionado</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PAKs Relacionados</relationshipLabel>
    <relationshipName>PAKs_Relacionados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Related_PQR__c.field-meta.xml
<CustomField>
    <fullName>ALK_Related_PQR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso PQR Relacionado</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>PAKs Relacionado</relationshipLabel>
    <relationshipName>CasosPQRRelacionados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ALK_ODS.recordType-meta.xml
<RecordType>
    <fullName>ALK_ODS</fullName>
    <active>true</active>
    <businessProcess>ODS</businessProcess>
    <label>ODS</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_PAK.recordType-meta.xml
<RecordType>
    <fullName>ALK_PAK</fullName>
    <active>true</active>
    <businessProcess>PAK</businessProcess>
    <label>PAK</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_QUEJA.recordType-meta.xml
<RecordType>
    <fullName>ALK_QUEJA</fullName>
    <active>true</active>
    <businessProcess>Quejas</businessProcess>
    <label>QUEJA</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_SOLICITUD.recordType-meta.xml
<RecordType>
    <fullName>ALK_SOLICITUD</fullName>
    <active>true</active>
    <businessProcess>SOLICITUDES</businessProcess>
    <label>SOLICITUD</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Persona Natural</label>
</RecordType>

force-app/main/default/classes/ALK_ProcessCreatedPakBatchTest.cls
@isTest public class ALK_ProcessCreatedPakBatchTest {
    
    @isTest static void test1() {
        
        Account a = new Account(FirstName = 'testAccountSA', 
                                LastName = 'Last', 
                                PersonEmail='test@test.com',
                                Phone='573005716885',
                                ALK_WHATSAPP__c = false,
                                ALK_SMS__c = false,
                                ALK_EMAIL__c = true,
                                RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId());
        insert a;
        
        Case solicitud = new Case(AccountId = a.Id, 
                              Origin = 'Solicitud Demanda', 
                              Priority = 'Media', 
                              Subject = 'SOLICITUD', 
                              Status = 'Nuevo',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_SOLICITUD').getRecordTypeId());
        insert solicitud;
        
        ALK_Invoice__c isolicitud = new alk_Invoice__c();
        isolicitud.ALK_Case__c = solicitud.Id;
        isolicitud.ALK_EAN__c = '12345';
        isolicitud.Name = '12345';        
        
        insert isolicitud;        
        
        Case queja = new Case(AccountId = a.Id, 
                              Origin = 'SIC Demanda', 
                              Priority = 'Media', 
                              Subject = 'Queja', 
                              Status = 'Nuevo',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_QUEJA').getRecordTypeId());
        insert queja;
        
        ALK_Invoice__c iQueja = new alk_Invoice__c();
        iQueja.ALK_Case__c = queja.Id;
        iQueja.ALK_EAN__c = '12345';
        iQueja.Name = '12345';        
        
        insert iQueja;
        
        Case ods = new Case(AccountId = a.Id, 
                              Origin = 'ODS Demanda', 
                              Priority = 'Media', 
                              Subject = 'ODS', 
                              Status = 'Nuevo',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_ODS').getRecordTypeId());        

        insert ods;
        
        ALK_Invoice__c iods = new alk_Invoice__c();
        iods.ALK_Case__c = ods.Id;
        iods.ALK_EAN__c = '12345';
        iods.Name = '12345';        
        
        insert iods; 
        
        Case pak = new Case(AccountId = a.Id,
                              Origin = 'PAk', 
                              Priority = 'Media', 
                              Subject = 'Autorización de Cambio PAK', 
                              Status = 'Baja',
                              ALK_Pak_Batch_Status__c = 'No procesado',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_PAK').getRecordTypeId());        

        insert pak;
        
        ALK_Invoice__c ipak = new alk_Invoice__c();
        ipak.ALK_Case__c = pak.Id;
        ipak.ALK_EAN__c = '12345';
        ipak.Name = '12345';        
        
        insert ipak; 
        
        Test.startTest();
        ALK_ProcessCreatedPakBatch b = new ALK_ProcessCreatedPakBatch();     
        Database.executeBatch(b);
        Test.stopTest();
        
        pak = [SELECT Id, ALK_Related_PQR__c, ALK_Related_ODS__c, ALK_Pak_Batch_Status__c FROM Case Where Id = :pak.Id];
        
        System.assertEquals(queja.Id, pak.ALK_Related_PQR__c);
        System.assertEquals(ods.Id, pak.ALK_Related_ODS__c);        
        System.assertEquals(pak.ALK_Pak_Batch_Status__c, 'ODS/PQR relacionados');        
    }

    @isTest static void testSchedule() {             
        Test.startTest();
        ALK_ProcessCreatedPakSchedule s = new ALK_ProcessCreatedPakSchedule();
		System.schedule('One shot', '0 0 8 13 2 ?', s);
        Test.stopTest();
    }    
    
    @isTest static void sendSupportEmailOnError() {
        Test.startTest();
        ALK_ProcessCreatedPakBatch b = new ALK_ProcessCreatedPakBatch();     
        Database.executeBatch(b); 
		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email, ExtendedStatus FROM AsyncApexJob Limit 1]; 
        b.sendSupportEmail(a);
        Test.stopTest();        
    }    
}