force-app/main/default/objects/ALK_Invoice__c/ALK_Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>No de la Factura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_Case__c.field-meta.xml
<CustomField>
    <fullName>ALK_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ALK_Invoice__c/fields/ALK_EAN__c.field-meta.xml
<CustomField>
    <fullName>ALK_EAN__c</fullName>
    <label>EAN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Approval_Number__c.field-meta.xml
<CustomField>
    <fullName>ALK_Approval_Number__c</fullName>
    <externalId>true</externalId>
    <label>Número de Aprobación</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Motivo_de_Cierre__c.field-meta.xml
<CustomField>
    <fullName>ALK_Motivo_de_Cierre__c</fullName>
    <description>El usuario selecciona el motivo por el cual desea cerrar el caso</description>
    <inlineHelpText>Por favor, seleccione el motivo por el cual desea cerrar el caso</inlineHelpText>
    <label>Motivo de Cierre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>A FAVOR DE CLIENTE ASUME ALKOSTO</fullName>
            </value>
            <value>
                <fullName>A FAVOR DE CLIENTE ASUME MARCA</fullName>
            </value>
            <value>
                <fullName>CLIENTE DESISTE DE RECLAMACIÓN</fullName>
            </value>
            <value>
                <fullName>NEGATIVA SOLICITUD DE CLIENTE</fullName>
            </value>
            <value>
                <fullName>PRODUCTO FUNCIONAL</fullName>
            </value>
            <value>
                <fullName>SIN CONTACTO CON CLIENTE</fullName>
            </value>
            <value>
                <fullName>SOLUCION CLIENTE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ALK_Pak_Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>ALK_Pak_Batch_Status__c</fullName>
    <label>Estado proceso batch Pak</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No procesado</fullName>
                <default>true</default>
                <label>No procesado</label>
            </value>
            <value>
                <fullName>ODS/PQR relacionados</fullName>
            </value>
            <value>
                <fullName>ODS/PQR Cerrados</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Estado__c.field-meta.xml
<CustomField>
    <fullName>Sub_Estado__c</fullName>
    <label>Sub-Estado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Almacenado en tienda</fullName>
            </value>
            <value>
                <fullName>Carta enviada</fullName>
            </value>
            <value>
                <fullName>Carta no entregada</fullName>
            </value>
            <value>
                <fullName>Cliente no contactado</fullName>
            </value>
            <value>
                <fullName>Cliente no recibe</fullName>
            </value>
            <value>
                <fullName>Cliente no recoge</fullName>
            </value>
            <value>
                <fullName>Cte Contactado Pte Recogida</fullName>
            </value>
            <value>
                <fullName>Destrucción</fullName>
            </value>
            <value>
                <fullName>Entregado Cliente</fullName>
            </value>
            <value>
                <fullName>Enviado a CENTR</fullName>
            </value>
            <value>
                <fullName>Enviado a Cliente</fullName>
            </value>
            <value>
                <fullName>Recibido en CENTR</fullName>
            </value>
            <value>
                <fullName>Retornado a Tienda</fullName>
            </value>
            <value>
                <fullName>Pendiente envío a CENTR</fullName>
            </value>
            <value>
                <fullName>Caso SIC</fullName>
            </value>
            <value>
                <fullName>En espera de Respuesta</fullName>
            </value>
            <value>
                <fullName>Cliente Informado</fullName>
            </value>
            <value>
                <fullName>Alkosto</fullName>
            </value>
            <value>
                <fullName>Marca</fullName>
            </value>
            <value>
                <fullName>Producto Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado Bono Cambio</fullName>
            </value>
            <value>
                <fullName>Entregado a Centro Servicio en Tienda</fullName>
            </value>
            <value>
                <fullName>Entregado a Centro Servicio en CENTR</fullName>
            </value>
            <value>
                <fullName>Recibo/Entrega - Falla</fullName>
            </value>
            <value>
                <fullName>Recibo/Entrega - Deteriorado/cosmetico</fullName>
            </value>
            <value>
                <fullName>Recibo/Entrega - Incompleto</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Enviado a Tienda</fullName>
            </value>
            <value>
                <fullName>En CENTR de tienda</fullName>
            </value>
            <value>
                <fullName>En muelle CAS pte validacion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ALK_ODS.recordType-meta.xml
<RecordType>
    <fullName>ALK_ODS</fullName>
    <active>true</active>
    <businessProcess>ODS</businessProcess>
    <label>ODS</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_PAK.recordType-meta.xml
<RecordType>
    <fullName>ALK_PAK</fullName>
    <active>true</active>
    <businessProcess>PAK</businessProcess>
    <label>PAK</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_QUEJA.recordType-meta.xml
<RecordType>
    <fullName>ALK_QUEJA</fullName>
    <active>true</active>
    <businessProcess>Quejas</businessProcess>
    <label>QUEJA</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ALK_SOLICITUD.recordType-meta.xml
<RecordType>
    <fullName>ALK_SOLICITUD</fullName>
    <active>true</active>
    <businessProcess>SOLICITUDES</businessProcess>
    <label>SOLICITUD</label>
</RecordType>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Persona Natural</label>
</RecordType>

force-app/main/default/classes/ALK_CloseRelatedCasesClosedPaksBatchTest.cls
@isTest public class ALK_CloseRelatedCasesClosedPaksBatchTest {
    @isTest static void test1() {
        Account a = new Account(FirstName = 'testAccountSA', 
                                LastName = 'Last', 
                                PersonEmail='test@test.com',
                                Phone='573005716885',
                                ALK_WHATSAPP__c = false,
                                ALK_SMS__c = false,
                                ALK_EMAIL__c = true,
                                RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId());
        insert a;
        
        Case solicitud = new Case(AccountId = a.Id, 
                              Origin = 'Solicitud Demanda', 
                              Priority = 'Media', 
                              Subject = 'SOLICITUD', 
                              Status = 'New',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_SOLICITUD').getRecordTypeId());
        insert solicitud;
        
        ALK_Invoice__c isolicitud = new alk_Invoice__c();
        isolicitud.ALK_Case__c = solicitud.Id;
        isolicitud.ALK_EAN__c = '12345';
        isolicitud.Name = '12345';        
        
        insert isolicitud;        
        
        Case queja = new Case(AccountId = a.Id, 
                              Origin = 'SIC Demanda', 
                              Priority = 'Media', 
                              Subject = 'Queja', 
                              Status = 'New',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_QUEJA').getRecordTypeId());
        insert queja;
        
        ALK_Invoice__c iQueja = new alk_Invoice__c();
        iQueja.ALK_Case__c = queja.Id;
        iQueja.ALK_EAN__c = '12345';
        iQueja.Name = '12345';        
        
        insert iQueja;
        
        Case ods = new Case(AccountId = a.Id, 
                              Origin = 'ODS Demanda', 
                              Priority = 'Media', 
                              Subject = 'ODS', 
                              Status = 'New',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_ODS').getRecordTypeId());        

        insert ods;
        
        ALK_Invoice__c iods = new alk_Invoice__c();
        iods.ALK_Case__c = ods.Id;
        iods.ALK_EAN__c = '12345';
        iods.Name = '12345';        
        
        insert iods; 
                
        Case pak = new Case(AccountId = a.Id,
                              Origin = 'PAk', 
                              Priority = 'Media', 
                              Subject = 'Autorización de Cambio PAK', 
                              Status = 'New',
                              ALK_Approval_Number__c = 'AP_91953',
                              ALK_Pak_Batch_Status__c = 'ODS/PQR relacionados',
                              RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ALK_PAK').getRecordTypeId());        

        insert pak;
        
        ALK_Invoice__c ipak = new alk_Invoice__c();
        ipak.ALK_Case__c = pak.Id;
        ipak.ALK_EAN__c = '12345';
        ipak.Name = '12345';        
        
        insert ipak; 
        
        pak.Status = 'Solicitud Finalizada con devolución';
        update pak;
        
        Test.startTest();
        ALK_CloseRelatedCasesClosedPaksBatch b = new ALK_CloseRelatedCasesClosedPaksBatch();     
        Database.executeBatch(b);
        Test.stopTest();
        
        pak = [SELECT Id, ALK_Pak_Batch_Status__c FROM Case Where Id = :pak.Id];
        ods = [SELECT Id, Status, Sub_Estado__c, ALK_Motivo_de_Cierre__c FROM Case Where Id = :ods.Id];
        queja = [SELECT Id, Status, ALK_Motivo_de_Cierre__c FROM Case Where Id = :queja.Id];
        solicitud = [SELECT Id, Status, ALK_Motivo_de_Cierre__c FROM Case Where Id = :solicitud.Id];
        
        System.assertEquals(queja.status, 'Cerrado');
        System.assertEquals(solicitud.status, 'Cerrado');        
        System.assertEquals(ods.status, 'Solución al Cliente');
        System.assertEquals(ods.Sub_Estado__c, 'Entregado Bono Cambio');        
        
        
        System.assertEquals(queja.ALK_Motivo_de_Cierre__c, 'A FAVOR DE CLIENTE ASUME ALKOSTO');
        System.assertEquals(solicitud.ALK_Motivo_de_Cierre__c, 'A FAVOR DE CLIENTE ASUME ALKOSTO');        
        System.assertEquals(ods.ALK_Motivo_de_Cierre__c, 'A FAVOR DE CLIENTE ASUME ALKOSTO');        
        
        System.assertEquals(pak.ALK_Pak_Batch_Status__c, 'ODS/PQR Cerrados');        
        
    }
    
    @isTest static void testSchedule() {             
        Test.startTest();
        ALK_CloseRelatedCasesClosedPaksScheduler s = new ALK_CloseRelatedCasesClosedPaksScheduler();
		System.schedule('One shot', '0 0 8 13 2 ?', s);
        Test.stopTest();
    }    
    
    @isTest static void sendSupportEmailOnError() {
        Test.startTest();
        ALK_CloseRelatedCasesClosedPaksBatch b = new ALK_CloseRelatedCasesClosedPaksBatch();     
        Database.executeBatch(b); 
		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email, ExtendedStatus FROM AsyncApexJob Limit 1]; 
        b.sendSupportEmail(a);
        Test.stopTest();        
    }  
}